// <auto-generated />
namespace CourtFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class allownullsinleaguecsvars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allownullsinleaguecsvars));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271929429_allow nulls in league.cs vars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
