// <auto-generated />
namespace CourtFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedavailabletimesandhourstobracketforscheduling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedavailabletimesandhourstobracketforscheduling));
        
        string IMigrationMetadata.Id
        {
            get { return "201903010125139_added available times and hours to bracket for scheduling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
