// <auto-generated />
namespace CourtFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class madeleaguecsmembersnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madeleaguecsmembersnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201902272346217_made league.cs members nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
