// <auto-generated />
namespace CourtFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedprofileimagefieldtoplayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedprofileimagefieldtoplayer));
        
        string IMigrationMetadata.Id
        {
            get { return "201902231856599_added profile image field to player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
